name: medics_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  flutter_native_splash: ^2.2.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#199a8e"
  color_dark: "#000000"
  image: "assets/splashimage.png"
  image_dark: "assets/splashimage.png"
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/
